name: ParticlesUI
main: IndoParticle\Main
version: 1.0.0
softdepend:
- FormAPI
api: 3.0.0
author: xSoapers, IndoDev
commands:
  pcrownheart:
    description: "Particle CrownHeart Command"
    permission: p.crownheart
    usage: /pcrownheart
  plaser:
    description: "Particle Laser Command"
    permission: p.laser
    usage: /plaser
  ptornado:
    description: "Particle Tornado Command"
    permission: p.tornado
    usage: /ptornado
  psboom:
    description: "Particle SonicBoom Command"
    permission: p.sboom
    usage: /psboom
  pdring:
    description: "Particle Dring Command"
    permission: p.dring
    usage: /pdring
   peffect:
    description: "Particle Spell Command"
    permission: p.ef
    usage: /pef
  pnote: 
    description: "Particle Note Command"
    permission: p.note
    usage: /pnote
  penc:
    description: "Particle Enchant Command"
    permission: p.enc
    usage: /penc
  pdust:
    description: "Partile Dust Command"
    permission: p.dust
    usage: /pdust
  prain:
    description: "Partile Rain Command"
    permission: p.rain
    usage: /prain
  pui:
    description: "Particle UICommand"
    permission: p.ui
    usage: /pui
    
    
permissions:
  p.crownheart:
    default: op
    description: Particle CrownHeart Command
  p.laser:
    default: op
    description: Particle Laser Command
  p.tornado:
    default: op
    description: Particle Tornado Command
  p.sboom:
    default: op
    description: Particle SonicBoom Command
  p.dring:
    default: op
    description: Particle Dring Command
  peffect:
    description: "Particle Spell Command"
    permission: p.ef
    usage: /pef
  pnote: 
    description: "Particle Note Command"
    permission: p.note
    usage: /pnote
  penc:
    description: "Particle Enchant Command"
    permission: p.enc
    usage: /penc
  pdust:
    description: "Partile Dust Command"
    permission: p.dust
    usage: /pdust
  prain:
    description: "Partile Rain Command"
    permission: p.rain
    usage: /prain
  pui:
    description: "Particle UI Command"
    permission: p.ui
    usage: /pui
    
    
permissions:
  p.crownheart:
    default: op
    description: Particle CrownHeart Command
  p.laser:
    default: op
    description: Particle Laser Command
  p.tornado:
    default: op
    description: Particle Tornado Command
  p.sboom:
    default: op
    description: Particle SonicBoom Command
  p.dring:
    default: op
    description: Particle Dring Command
  p.ef:
    default: op
    description: Particle Speel Command
  p.note:
    default: op
    description: Particle Note Command
  p.enc:
    default: op
    description: Particle Enchant Command
  p.dust:
    defualt: op
    description: Particle Dust Command
  p.rain:
    defualt: op
    description: Particle Rain Command
  p.ui:
    default: op
    description: Particle UI Command
